### PR TITLE
Possibility to override doc_type

### PR DESCRIPTION
**Pull request by luiscoms**
I want to pass doc_type kwarg on insert method.
Currently, this value is overridden by `kwargs.update(self._es_args(resource))`, so I changed order.

> I recommend to update this method on other branches too

### CODE REVIEW

**Comment by luiscoms** [comment]
Any considerations?

**Comment by petrjasek** [comment]
looks ok to me

**Comment by petrjasek** [comment]
let me just check that failing build first so I can merge it with green checks

**Comment by luiscoms** [comment]
You can try to use services as [travis documentation](https://docs.travis-ci.com/user/database-setup/#installing-specific-versions-of-elasticsearch) allows

**Comment by luiscoms** [comment]
Hi @petrjasek tests are now passing

**Comment by petrjasek** [comment]
can you pls rebase without those travis changes? it should be fixed now on master

**Comment by luiscoms** [comment]
Well done

**Pull request merged**
