### PR TITLE
replaced datasource with resource in config.DOMAIN[]

### PR DESCRIPTION
**Pull request by ancafarcas**

### CODE REVIEW

**Comment by petrjasek** [comment]
hey @ancafarcas , why this change?

**Comment by ancafarcas** [comment]
We had some issues on liveblog with the date format for "published_date" on posts. Instead of the format   "2015-06-02T09:50:04+0000" we have obtained the format "2015-06-02T09:50:04+00:00" So, with this change the format is now homogeneous.

**Comment by petrjasek** [comment]
so in case you have 2 resources for single collection it's using now the base schema and not the one from queried resource right?

**Comment by ancafarcas** [comment]
yes, that's right

**Comment by petrjasek** [comment]
i've made it to use both, otherwise it would break superdesk. thx

**Comment by ancafarcas** [comment]
OK. It works well, thanks :)

**Pull request closed without merging**
